/** Dữ liệu khởi tạo — đồng bộ với frontend mock */
export const SEED_CATEGORIES = [
  {
    categoryId: '1',
    slug: 'dam-cong-so',
    name: 'Đầm công sở',
    image: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=800&h=1067&fit=crop&q=80',
  },
  {
    categoryId: '2',
    slug: 'ao-cong-so',
    name: 'Áo công sở',
    image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&h=1067&fit=crop&q=80',
  },
  {
    categoryId: '3',
    slug: 'vest',
    name: 'Vest',
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&h=1067&fit=crop&q=80',
  },
  {
    categoryId: '4',
    slug: 'phu-kien',
    name: 'Phụ kiện',
    image: 'https://images.unsplash.com/photo-1611601322175-ef8ec8c85f01?w=800&h=1067&fit=crop&q=80',
  },
];

export const SEED_PRODUCTS = [
  {
    productId: 'pdp-001',
    slug: 'dam-midi-aurelie',
    sku: 'TN-AUR-2603',
    title: 'Đầm midi Aurelie',
    categorySlug: 'dam-cong-so',
    collection: 'Bộ sưu tập Thu 2026',
    price: 2680000,
    originalPrice: 3200000,
    rating: 4.9,
    reviews: 247,
    sold: 245,
    image: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=500&h=700&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=500&h=700&fit=crop',
      'https://images.unsplash.com/photo-1611601322175-ef8ec8c85f01?w=500&h=700&fit=crop',
      'https://images.unsplash.com/photo-1520975954732-35dd22299614?w=500&h=700&fit=crop',
      'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=500&h=700&fit=crop',
    ],
    colors: [
      { name: 'Nâu hạt dẻ', code: '#8B6B43' },
      { name: 'Đen', code: '#1A1A1A' },
      { name: 'Trắng', code: '#F5F5F5' },
      { name: 'Xanh than', code: '#2C3E50' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S', available: true },
      { size: 'M', available: true },
      { size: 'L', available: true },
      { size: 'XL', available: false },
    ],
    description:
      'Đầm midi sang trọng được làm từ lụa tơ tằm cao cấp, phù hợp cho những dịp công sở hoặc dạo phố.',
    material: '100% lụa Habotai · 19mm',
    origin: 'Chế tác thủ công tại Hà Nội',
    lining: 'Voan lụa cotton',
    fit: 'Văn phòng · Sự kiện · Dạo phố',
    modelHeight: '1m68 mặc size S',
    inStock: true,
    isSale: true,
    isNew: false,
  },
  {
    productId: 'pdp-004',
    slug: 'dam-lech-vai-provence',
    sku: 'DAM-DBL-004',
    title: 'Đầm lệch vai Provence',
    categorySlug: 'dam-cong-so',
    collection: 'Collection Chic',
    price: 1890000,
    originalPrice: 2290000,
    rating: 4.6,
    reviews: 42,
    sold: 76,
    image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=500&h=700&fit=crop',
    images: [],
    colors: [
      { name: 'Trắng', code: '#FFFFFF' },
      { name: 'Hồng đất', code: '#D4A5A5' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S', available: true },
      { size: 'M', available: true },
      { size: 'L', available: true },
      { size: 'XL', available: true },
    ],
    description: 'Đầm lệch vai tinh tế, hoàn hảo cho dạo phố hoặc sự kiện đặc biệt.',
    material: 'Cotton 100%',
    origin: 'Thiết kế tại Hà Nội, may tại Việt Nam',
    fit: 'Form ôm nhẹ',
    modelHeight: '167cm, size S',
    inStock: true,
    isSale: true,
    isNew: false,
  },
  {
    productId: 'pdp-006',
    slug: 'dam-xoe-lua-vivienne',
    sku: 'DAM-SLK-006',
    title: 'Đầm xòe lụa Vivienne',
    categorySlug: 'dam-cong-so',
    collection: 'Spring 2024',
    price: 2450000,
    originalPrice: 3100000,
    rating: 4.8,
    reviews: 67,
    sold: 112,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&h=700&fit=crop',
    images: [],
    colors: [
      { name: 'Hồng đất', code: '#D4A5A5' },
      { name: 'Xanh sâu', code: '#4F6B3A' },
    ],
    sizes: [
      { size: 'XS', available: false },
      { size: 'S', available: true },
      { size: 'M', available: true },
      { size: 'L', available: true },
      { size: 'XL', available: false },
    ],
    description: 'Đầm xòe lụa với thiết kế thanh lịch, hoàn hảo cho sự kiện đặc biệt.',
    material: 'Lụa tơ tằm 100%',
    origin: 'Thiết kế tại Hà Nội, may tại Việt Nam',
    fit: 'Form xòe nhẹ',
    modelHeight: '167cm, size M',
    inStock: true,
    isSale: true,
    isNew: false,
  },
  {
    productId: 'pdp-008',
    slug: 'dam-pleats-ophelie',
    sku: 'DAM-PLT-008',
    title: 'Đầm pleats tay lỡ Ophélie',
    categorySlug: 'dam-cong-so',
    collection: 'Collection Chic',
    price: 1690000,
    rating: 4.7,
    reviews: 34,
    sold: 58,
    image: 'https://images.unsplash.com/photo-1571513722275-4b41940f54b8?w=500&h=700&fit=crop',
    images: [],
    colors: [
      { name: 'Đen', code: '#1A1A1A' },
      { name: 'Navy', code: '#1A3A52' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S', available: true },
      { size: 'M', available: true },
      { size: 'L', available: true },
      { size: 'XL', available: true },
    ],
    description: 'Đầm pleats tay lỡ với thiết kế cổ điển và sang trọng.',
    material: 'Cotton linen 70/30',
    origin: 'Thiết kế tại Hà Nội, may tại Việt Nam',
    fit: 'Form bó vừa',
    modelHeight: '167cm, size M',
    inStock: true,
    isSale: false,
    isNew: false,
  },
  {
    productId: 'pdp-002',
    slug: 'ao-so-mi-lua-solange',
    sku: 'AO-SLK-002',
    title: 'Áo sơ mi lụa Solange',
    categorySlug: 'ao-cong-so',
    collection: 'Spring 2024',
    price: 1290000,
    originalPrice: 1690000,
    rating: 4.7,
    reviews: 89,
    sold: 167,
    image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=500&h=700&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=500&h=700&fit=crop',
      'https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?w=500&h=700&fit=crop',
    ],
    colors: [
      { name: 'Trắng', code: '#FFFFFF' },
      { name: 'Hồng nhạt', code: '#F8B4D6' },
      { name: 'Xanh nhạt', code: '#A8D5E2' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S', available: true },
      { size: 'M', available: true },
      { size: 'L', available: true },
      { size: 'XL', available: true },
    ],
    description: 'Áo sơ mi lụa thanh lịch, hoàn hảo cho công sở hoặc dạo phố.',
    material: 'Lụa tơ tằm 100%',
    origin: 'Thiết kế tại Hà Nội, may tại Việt Nam',
    fit: 'Form suông nhẹ',
    modelHeight: '167cm, size S',
    inStock: true,
    isSale: true,
    isNew: true,
  },
  {
    productId: 'pdp-003',
    slug: 'vest-dao-pho-margot',
    sku: 'VES-BLZ-003',
    title: 'Vest dạo phố Margot',
    categorySlug: 'vest',
    collection: 'Collection Chic',
    price: 2290000,
    rating: 4.8,
    reviews: 56,
    sold: 98,
    image: 'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?w=500&h=700&fit=crop',
    images: ['https://images.unsplash.com/photo-1596783074918-c84cb06531ca?w=500&h=700&fit=crop'],
    colors: [
      { name: 'Đen', code: '#1A1A1A' },
      { name: 'Nâu', code: '#8B6B43' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S', available: true },
      { size: 'M', available: true },
      { size: 'L', available: true },
      { size: 'XL', available: false },
    ],
    description: 'Vest dạo phố cơ bản nhưng tinh tế.',
    material: 'Cotton linen blend 50/50',
    origin: 'Thiết kế tại Hà Nội, may tại Việt Nam',
    fit: 'Form bó nhẹ',
    modelHeight: '167cm, size M',
    inStock: true,
    isSale: false,
    isNew: true,
  },
  {
    productId: 'pdp-007',
    slug: 'blouse-cotton-amelie',
    sku: 'AO-BLZ-007',
    title: 'Blouse cotton trắng Amélie',
    categorySlug: 'ao-cong-so',
    collection: 'Essentials',
    price: 590000,
    rating: 4.5,
    reviews: 178,
    sold: 456,
    image: 'https://images.unsplash.com/photo-1588117305388-c2631a279f82?w=500&h=700&fit=crop',
    images: [],
    colors: [
      { name: 'Trắng', code: '#FFFFFF' },
      { name: 'Nâu nhạt', code: '#C9A87E' },
    ],
    sizes: [
      { size: 'XS', available: true },
      { size: 'S', available: true },
      { size: 'M', available: true },
      { size: 'L', available: true },
      { size: 'XL', available: true },
    ],
    description: 'Blouse cotton cơ bản, thoáng khí và dễ kết hợp.',
    material: 'Cotton 100%',
    origin: 'Thiết kế tại Hà Nội, may tại Việt Nam',
    fit: 'Form suông vừa',
    modelHeight: '167cm, size S',
    inStock: true,
    isSale: false,
    isNew: true,
  },
];

export const SEED_VOUCHERS = [
  {
    voucherId: 'v0',
    code: 'THUMOI200',
    description: 'Giảm 200.000đ cho khách hàng mới',
    discount: 200_000,
    discountType: 'fixed' as const,
    minPurchase: 1_500_000,
    maxUses: 5000,
    usedCount: 891,
    expiresAt: new Date('2026-12-31'),
    isActive: true,
  },
  {
    voucherId: 'v1',
    code: 'NEWCUSTOMER20',
    description: 'Giảm 20% cho khách hàng mới',
    discount: 20,
    discountType: 'percentage' as const,
    minPurchase: 500_000,
    maxUses: 1000,
    usedCount: 342,
    expiresAt: new Date('2026-12-31'),
    isActive: true,
  },
];
